# fly.toml app configuration file generated for k7-portfolio on 2024-09-08T19:09:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'k7-portfolio'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
